# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NetdriveConnectorWidget.ui'
#
# Created: Sat Mar 29 07:59:21 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NetdriveConnectorWidget(object):
    def setupUi(self, NetdriveConnectorWidget):
        NetdriveConnectorWidget.setObjectName(_fromUtf8("NetdriveConnectorWidget"))
        NetdriveConnectorWidget.resize(731, 607)
        self.gridLayout_2 = QtGui.QGridLayout(NetdriveConnectorWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.connectionsGroupBox = QtGui.QGroupBox(NetdriveConnectorWidget)
        self.connectionsGroupBox.setObjectName(_fromUtf8("connectionsGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.connectionsGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.connectionsTableLegendLbl = QtGui.QLabel(self.connectionsGroupBox)
        self.connectionsTableLegendLbl.setObjectName(_fromUtf8("connectionsTableLegendLbl"))
        self.gridLayout_3.addWidget(self.connectionsTableLegendLbl, 0, 0, 1, 1)
        self.removeBtn = QtGui.QPushButton(self.connectionsGroupBox)
        self.removeBtn.setObjectName(_fromUtf8("removeBtn"))
        self.gridLayout_3.addWidget(self.removeBtn, 3, 1, 1, 1)
        self.connectBtn = QtGui.QPushButton(self.connectionsGroupBox)
        self.connectBtn.setObjectName(_fromUtf8("connectBtn"))
        self.gridLayout_3.addWidget(self.connectBtn, 1, 1, 1, 1)
        self.disconnectBtn = QtGui.QPushButton(self.connectionsGroupBox)
        self.disconnectBtn.setObjectName(_fromUtf8("disconnectBtn"))
        self.gridLayout_3.addWidget(self.disconnectBtn, 2, 1, 1, 1)
        self.connectionsListWidget = QtGui.QListWidget(self.connectionsGroupBox)
        self.connectionsListWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.connectionsListWidget.setAlternatingRowColors(False)
        self.connectionsListWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.connectionsListWidget.setObjectName(_fromUtf8("connectionsListWidget"))
        self.gridLayout_3.addWidget(self.connectionsListWidget, 1, 0, 4, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.connectionsGroupBox, 0, 0, 1, 1)
        self.sftpGroupBox = QtGui.QGroupBox(NetdriveConnectorWidget)
        self.sftpGroupBox.setObjectName(_fromUtf8("sftpGroupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.sftpGroupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.sftpPathLineEdit = QtGui.QLineEdit(self.sftpGroupBox)
        self.sftpPathLineEdit.setObjectName(_fromUtf8("sftpPathLineEdit"))
        self.gridLayout_6.addWidget(self.sftpPathLineEdit, 0, 8, 1, 1)
        self.sftpPortSpinBox = QtGui.QSpinBox(self.sftpGroupBox)
        self.sftpPortSpinBox.setMinimum(1)
        self.sftpPortSpinBox.setMaximum(6000)
        self.sftpPortSpinBox.setProperty("value", 22)
        self.sftpPortSpinBox.setObjectName(_fromUtf8("sftpPortSpinBox"))
        self.gridLayout_6.addWidget(self.sftpPortSpinBox, 0, 6, 1, 1)
        self.sftpPortSeparatorLbl = QtGui.QLabel(self.sftpGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sftpPortSeparatorLbl.setFont(font)
        self.sftpPortSeparatorLbl.setObjectName(_fromUtf8("sftpPortSeparatorLbl"))
        self.gridLayout_6.addWidget(self.sftpPortSeparatorLbl, 0, 5, 1, 1)
        self.sftpPathSeparatorLbl = QtGui.QLabel(self.sftpGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sftpPathSeparatorLbl.setFont(font)
        self.sftpPathSeparatorLbl.setObjectName(_fromUtf8("sftpPathSeparatorLbl"))
        self.gridLayout_6.addWidget(self.sftpPathSeparatorLbl, 0, 7, 1, 1)
        self.sftpMountpointLineEdit = QtGui.QLineEdit(self.sftpGroupBox)
        self.sftpMountpointLineEdit.setReadOnly(True)
        self.sftpMountpointLineEdit.setObjectName(_fromUtf8("sftpMountpointLineEdit"))
        self.gridLayout_6.addWidget(self.sftpMountpointLineEdit, 1, 1, 1, 8)
        self.sftpLbl = QtGui.QLabel(self.sftpGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sftpLbl.setFont(font)
        self.sftpLbl.setObjectName(_fromUtf8("sftpLbl"))
        self.gridLayout_6.addWidget(self.sftpLbl, 0, 0, 1, 1)
        self.sftpMountpointBtn = QtGui.QPushButton(self.sftpGroupBox)
        self.sftpMountpointBtn.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../usr/share/icons/oxygen/16x16/places/folder-network.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sftpMountpointBtn.setIcon(icon)
        self.sftpMountpointBtn.setObjectName(_fromUtf8("sftpMountpointBtn"))
        self.gridLayout_6.addWidget(self.sftpMountpointBtn, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.sftpGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 3, 1, 1)
        self.sftpPasswordLbl = QtGui.QLabel(self.sftpGroupBox)
        self.sftpPasswordLbl.setObjectName(_fromUtf8("sftpPasswordLbl"))
        self.gridLayout_6.addWidget(self.sftpPasswordLbl, 3, 0, 1, 2)
        self.sftpUsernameLineEdit = QtGui.QLineEdit(self.sftpGroupBox)
        self.sftpUsernameLineEdit.setObjectName(_fromUtf8("sftpUsernameLineEdit"))
        self.gridLayout_6.addWidget(self.sftpUsernameLineEdit, 0, 1, 1, 2)
        self.sftpHostnameLineEdit = QtGui.QLineEdit(self.sftpGroupBox)
        self.sftpHostnameLineEdit.setObjectName(_fromUtf8("sftpHostnameLineEdit"))
        self.gridLayout_6.addWidget(self.sftpHostnameLineEdit, 0, 4, 1, 1)
        self.sftpPasswordLineEdit = QtGui.QLineEdit(self.sftpGroupBox)
        self.sftpPasswordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.sftpPasswordLineEdit.setObjectName(_fromUtf8("sftpPasswordLineEdit"))
        self.gridLayout_6.addWidget(self.sftpPasswordLineEdit, 3, 2, 1, 3)
        self.addSftpBtn = QtGui.QPushButton(self.sftpGroupBox)
        self.addSftpBtn.setObjectName(_fromUtf8("addSftpBtn"))
        self.gridLayout_6.addWidget(self.addSftpBtn, 4, 0, 1, 3)
        self.sftpPasswordlessCheckBox = QtGui.QCheckBox(self.sftpGroupBox)
        self.sftpPasswordlessCheckBox.setEnabled(True)
        self.sftpPasswordlessCheckBox.setCheckable(True)
        self.sftpPasswordlessCheckBox.setChecked(True)
        self.sftpPasswordlessCheckBox.setObjectName(_fromUtf8("sftpPasswordlessCheckBox"))
        self.gridLayout_6.addWidget(self.sftpPasswordlessCheckBox, 2, 0, 1, 5)
        self.sftpAutoMountCheckBox = QtGui.QCheckBox(self.sftpGroupBox)
        self.sftpAutoMountCheckBox.setObjectName(_fromUtf8("sftpAutoMountCheckBox"))
        self.gridLayout_6.addWidget(self.sftpAutoMountCheckBox, 2, 6, 1, 3)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.sftpGroupBox, 1, 0, 1, 1)
        self.webdavGroupBox = QtGui.QGroupBox(NetdriveConnectorWidget)
        self.webdavGroupBox.setObjectName(_fromUtf8("webdavGroupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.webdavGroupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.addWebdavBtn = QtGui.QPushButton(self.webdavGroupBox)
        self.addWebdavBtn.setObjectName(_fromUtf8("addWebdavBtn"))
        self.gridLayout_8.addWidget(self.addWebdavBtn, 7, 0, 1, 3)
        self.webdavUsernameLbl = QtGui.QLabel(self.webdavGroupBox)
        self.webdavUsernameLbl.setObjectName(_fromUtf8("webdavUsernameLbl"))
        self.gridLayout_8.addWidget(self.webdavUsernameLbl, 5, 0, 1, 2)
        self.webdavPortSeparatorLbl = QtGui.QLabel(self.webdavGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.webdavPortSeparatorLbl.setFont(font)
        self.webdavPortSeparatorLbl.setObjectName(_fromUtf8("webdavPortSeparatorLbl"))
        self.gridLayout_8.addWidget(self.webdavPortSeparatorLbl, 2, 3, 1, 1)
        self.webdavPathSeparatorLbl = QtGui.QLabel(self.webdavGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.webdavPathSeparatorLbl.setFont(font)
        self.webdavPathSeparatorLbl.setObjectName(_fromUtf8("webdavPathSeparatorLbl"))
        self.gridLayout_8.addWidget(self.webdavPathSeparatorLbl, 2, 5, 1, 1)
        self.webdavPasswordLineEdit = QtGui.QLineEdit(self.webdavGroupBox)
        self.webdavPasswordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.webdavPasswordLineEdit.setObjectName(_fromUtf8("webdavPasswordLineEdit"))
        self.gridLayout_8.addWidget(self.webdavPasswordLineEdit, 6, 2, 1, 1)
        self.webdavUsernameLineEdit = QtGui.QLineEdit(self.webdavGroupBox)
        self.webdavUsernameLineEdit.setObjectName(_fromUtf8("webdavUsernameLineEdit"))
        self.gridLayout_8.addWidget(self.webdavUsernameLineEdit, 5, 2, 1, 1)
        self.webdavProtocolLbl = QtGui.QLabel(self.webdavGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.webdavProtocolLbl.setFont(font)
        self.webdavProtocolLbl.setObjectName(_fromUtf8("webdavProtocolLbl"))
        self.gridLayout_8.addWidget(self.webdavProtocolLbl, 2, 0, 1, 1)
        self.webdavPortSpinBox = QtGui.QSpinBox(self.webdavGroupBox)
        self.webdavPortSpinBox.setMinimum(1)
        self.webdavPortSpinBox.setMaximum(6000)
        self.webdavPortSpinBox.setProperty("value", 80)
        self.webdavPortSpinBox.setObjectName(_fromUtf8("webdavPortSpinBox"))
        self.gridLayout_8.addWidget(self.webdavPortSpinBox, 2, 4, 1, 1)
        self.webdavUriLineEdit = QtGui.QLineEdit(self.webdavGroupBox)
        self.webdavUriLineEdit.setObjectName(_fromUtf8("webdavUriLineEdit"))
        self.gridLayout_8.addWidget(self.webdavUriLineEdit, 2, 6, 1, 1)
        self.webdavServerUrlLineEdit = QtGui.QLineEdit(self.webdavGroupBox)
        self.webdavServerUrlLineEdit.setObjectName(_fromUtf8("webdavServerUrlLineEdit"))
        self.gridLayout_8.addWidget(self.webdavServerUrlLineEdit, 2, 1, 1, 2)
        self.webdavPasswordLbl = QtGui.QLabel(self.webdavGroupBox)
        self.webdavPasswordLbl.setObjectName(_fromUtf8("webdavPasswordLbl"))
        self.gridLayout_8.addWidget(self.webdavPasswordLbl, 6, 0, 1, 2)
        self.webdavMountpointBtn = QtGui.QPushButton(self.webdavGroupBox)
        self.webdavMountpointBtn.setText(_fromUtf8(""))
        self.webdavMountpointBtn.setIcon(icon)
        self.webdavMountpointBtn.setObjectName(_fromUtf8("webdavMountpointBtn"))
        self.gridLayout_8.addWidget(self.webdavMountpointBtn, 3, 0, 1, 1)
        self.webdavMountpointLineEdit = QtGui.QLineEdit(self.webdavGroupBox)
        self.webdavMountpointLineEdit.setReadOnly(True)
        self.webdavMountpointLineEdit.setObjectName(_fromUtf8("webdavMountpointLineEdit"))
        self.gridLayout_8.addWidget(self.webdavMountpointLineEdit, 3, 1, 1, 6)
        self.webdavSavePasswordCheckBox = QtGui.QCheckBox(self.webdavGroupBox)
        self.webdavSavePasswordCheckBox.setChecked(True)
        self.webdavSavePasswordCheckBox.setObjectName(_fromUtf8("webdavSavePasswordCheckBox"))
        self.gridLayout_8.addWidget(self.webdavSavePasswordCheckBox, 4, 0, 1, 3)
        self.httpRadioButton = QtGui.QRadioButton(self.webdavGroupBox)
        self.httpRadioButton.setChecked(True)
        self.httpRadioButton.setObjectName(_fromUtf8("httpRadioButton"))
        self.gridLayout_8.addWidget(self.httpRadioButton, 0, 0, 1, 7)
        self.httpsRadioButton = QtGui.QRadioButton(self.webdavGroupBox)
        self.httpsRadioButton.setObjectName(_fromUtf8("httpsRadioButton"))
        self.gridLayout_8.addWidget(self.httpsRadioButton, 1, 0, 1, 7)
        self.webdavAutoMountCheckBox = QtGui.QCheckBox(self.webdavGroupBox)
        self.webdavAutoMountCheckBox.setObjectName(_fromUtf8("webdavAutoMountCheckBox"))
        self.gridLayout_8.addWidget(self.webdavAutoMountCheckBox, 4, 4, 1, 3)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.webdavGroupBox, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(NetdriveConnectorWidget)
        QtCore.QObject.connect(self.addSftpBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), NetdriveConnectorWidget.addSftpBtnClicked)
        QtCore.QObject.connect(self.addWebdavBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), NetdriveConnectorWidget.addWebdavBtnClicked)
        QtCore.QObject.connect(self.sftpMountpointBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), NetdriveConnectorWidget.sftpMountpointBtnClicked)
        QtCore.QObject.connect(self.webdavMountpointBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), NetdriveConnectorWidget.webdavMountpointBtnClicked)
        QtCore.QObject.connect(self.connectBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), NetdriveConnectorWidget.connectBtnClicked)
        QtCore.QObject.connect(self.disconnectBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), NetdriveConnectorWidget.disconnectBtnClicked)
        QtCore.QObject.connect(self.removeBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), NetdriveConnectorWidget.removeBtnClicked)
        QtCore.QObject.connect(self.httpRadioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), NetdriveConnectorWidget.httpRadioBtnClicked)
        QtCore.QObject.connect(self.httpsRadioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), NetdriveConnectorWidget.httpsRadioBtnClicked)
        QtCore.QObject.connect(self.sftpPasswordlessCheckBox, QtCore.SIGNAL(_fromUtf8("clicked()")), NetdriveConnectorWidget.sftpPasswordlessCheckBoxClicked)
        QtCore.QObject.connect(self.webdavSavePasswordCheckBox, QtCore.SIGNAL(_fromUtf8("clicked()")), NetdriveConnectorWidget.webdavSavePasswordCheckBoxClicked)
        QtCore.QMetaObject.connectSlotsByName(NetdriveConnectorWidget)
        NetdriveConnectorWidget.setTabOrder(self.connectionsListWidget, self.connectBtn)
        NetdriveConnectorWidget.setTabOrder(self.connectBtn, self.disconnectBtn)
        NetdriveConnectorWidget.setTabOrder(self.disconnectBtn, self.removeBtn)
        NetdriveConnectorWidget.setTabOrder(self.removeBtn, self.sftpUsernameLineEdit)
        NetdriveConnectorWidget.setTabOrder(self.sftpUsernameLineEdit, self.sftpHostnameLineEdit)
        NetdriveConnectorWidget.setTabOrder(self.sftpHostnameLineEdit, self.sftpPortSpinBox)
        NetdriveConnectorWidget.setTabOrder(self.sftpPortSpinBox, self.sftpPathLineEdit)
        NetdriveConnectorWidget.setTabOrder(self.sftpPathLineEdit, self.sftpMountpointBtn)
        NetdriveConnectorWidget.setTabOrder(self.sftpMountpointBtn, self.sftpMountpointLineEdit)
        NetdriveConnectorWidget.setTabOrder(self.sftpMountpointLineEdit, self.sftpPasswordlessCheckBox)
        NetdriveConnectorWidget.setTabOrder(self.sftpPasswordlessCheckBox, self.sftpAutoMountCheckBox)
        NetdriveConnectorWidget.setTabOrder(self.sftpAutoMountCheckBox, self.sftpPasswordLineEdit)
        NetdriveConnectorWidget.setTabOrder(self.sftpPasswordLineEdit, self.addSftpBtn)
        NetdriveConnectorWidget.setTabOrder(self.addSftpBtn, self.httpRadioButton)
        NetdriveConnectorWidget.setTabOrder(self.httpRadioButton, self.httpsRadioButton)
        NetdriveConnectorWidget.setTabOrder(self.httpsRadioButton, self.webdavServerUrlLineEdit)
        NetdriveConnectorWidget.setTabOrder(self.webdavServerUrlLineEdit, self.webdavPortSpinBox)
        NetdriveConnectorWidget.setTabOrder(self.webdavPortSpinBox, self.webdavUriLineEdit)
        NetdriveConnectorWidget.setTabOrder(self.webdavUriLineEdit, self.webdavMountpointBtn)
        NetdriveConnectorWidget.setTabOrder(self.webdavMountpointBtn, self.webdavMountpointLineEdit)
        NetdriveConnectorWidget.setTabOrder(self.webdavMountpointLineEdit, self.webdavSavePasswordCheckBox)
        NetdriveConnectorWidget.setTabOrder(self.webdavSavePasswordCheckBox, self.webdavAutoMountCheckBox)
        NetdriveConnectorWidget.setTabOrder(self.webdavAutoMountCheckBox, self.webdavUsernameLineEdit)
        NetdriveConnectorWidget.setTabOrder(self.webdavUsernameLineEdit, self.webdavPasswordLineEdit)
        NetdriveConnectorWidget.setTabOrder(self.webdavPasswordLineEdit, self.addWebdavBtn)

    def retranslateUi(self, NetdriveConnectorWidget):
        NetdriveConnectorWidget.setWindowTitle(_translate("NetdriveConnectorWidget", "Form", None))
        self.connectionsGroupBox.setTitle(_translate("NetdriveConnectorWidget", "Connections", None))
        self.connectionsTableLegendLbl.setText(_translate("NetdriveConnectorWidget", "Syntax: <Remote URL> <Local mount point> <filesystem type> <options> <dump> <check>  ", None))
        self.removeBtn.setText(_translate("NetdriveConnectorWidget", "Remove", None))
        self.connectBtn.setText(_translate("NetdriveConnectorWidget", "Connect", None))
        self.disconnectBtn.setText(_translate("NetdriveConnectorWidget", "Disconnect", None))
        self.sftpGroupBox.setTitle(_translate("NetdriveConnectorWidget", "Add SFTP Connection", None))
        self.sftpPathLineEdit.setPlaceholderText(_translate("NetdriveConnectorWidget", "path", None))
        self.sftpPortSeparatorLbl.setText(_translate("NetdriveConnectorWidget", ":", None))
        self.sftpPathSeparatorLbl.setText(_translate("NetdriveConnectorWidget", "/", None))
        self.sftpLbl.setText(_translate("NetdriveConnectorWidget", "sftp://", None))
        self.label.setText(_translate("NetdriveConnectorWidget", "@", None))
        self.sftpPasswordLbl.setText(_translate("NetdriveConnectorWidget", "SFTP password", None))
        self.sftpUsernameLineEdit.setPlaceholderText(_translate("NetdriveConnectorWidget", "username", None))
        self.sftpHostnameLineEdit.setPlaceholderText(_translate("NetdriveConnectorWidget", "hostname", None))
        self.addSftpBtn.setText(_translate("NetdriveConnectorWidget", "Add SFTP Connection", None))
        self.sftpPasswordlessCheckBox.setText(_translate("NetdriveConnectorWidget", "Password-less login (use ssh key)", None))
        self.sftpAutoMountCheckBox.setText(_translate("NetdriveConnectorWidget", "Auto-mount at login", None))
        self.webdavGroupBox.setTitle(_translate("NetdriveConnectorWidget", "Add WebDAV Connection", None))
        self.addWebdavBtn.setText(_translate("NetdriveConnectorWidget", "Add WebDAV connection", None))
        self.webdavUsernameLbl.setText(_translate("NetdriveConnectorWidget", "Username", None))
        self.webdavPortSeparatorLbl.setText(_translate("NetdriveConnectorWidget", ":", None))
        self.webdavPathSeparatorLbl.setText(_translate("NetdriveConnectorWidget", "/", None))
        self.webdavProtocolLbl.setText(_translate("NetdriveConnectorWidget", "http://", None))
        self.webdavUriLineEdit.setPlaceholderText(_translate("NetdriveConnectorWidget", "webdav URI", None))
        self.webdavServerUrlLineEdit.setPlaceholderText(_translate("NetdriveConnectorWidget", "server URL", None))
        self.webdavPasswordLbl.setText(_translate("NetdriveConnectorWidget", "Password", None))
        self.webdavSavePasswordCheckBox.setText(_translate("NetdriveConnectorWidget", "Save password", None))
        self.httpRadioButton.setText(_translate("NetdriveConnectorWidget", "HTTP (unencrypted connection)", None))
        self.httpsRadioButton.setText(_translate("NetdriveConnectorWidget", "HTTPS (SSL encrypted connection)", None))
        self.webdavAutoMountCheckBox.setText(_translate("NetdriveConnectorWidget", "Auto-mount at login", None))

