#! /usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'netdrive-connector==1.3','console_scripts','netdrive-connector'
__requires__ = 'netdrive-connector==1.3'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('netdrive-connector==1.3', 'console_scripts', 'netdrive-connector')()
    )
